title: Farhana Islam
description: Hi, I’m Farhana. A PhD candidate at the Department of Pharmacology and Toxicology at the University of Toronto. My doctoral research, in the field of Psychiatric Pharmacogenetics, focuses on identifying genetic variants contributing to antidepressant and antipsychotic drug pharmacokinetics and outcome in individuals with depression and schizophrenia. I conduct my research at the Pharmacogenetics Research Clinic at the Centre for Addiction and Mental Health (CAMH).
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
